name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: gofmt -w ./cmd ./internal ./pkg
      - run: git diff --exit-code
      - run: go test ./...
      - run: go test -race ./...
      - run: go vet ./...
      - run: GOOS=linux GOARCH=amd64 go build ./cmd/edge-agent ./cmd/edge-agentctl ./cmd/device-simulator
      - run: GOOS=linux GOARCH=arm64 go build ./cmd/edge-agent ./cmd/edge-agentctl ./cmd/device-simulator
